-- setup
PRAGMA foreign_keys = ON;

CREATE TABLE Games ( 
    Id INTEGER PRIMARY KEY AUTOINCREMENT, 
    Name TEXT NOT NULL, 
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP 
); 

CREATE TABLE Trainers (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    GameId INTEGER NOT NULL REFERENCES Games (Id) ON DELETE CASCADE,
    Name TEXT NOT NULL
);

CREATE TABLE Routes (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    GameId INTEGER NOT NULL REFERENCES Games (Id) ON DELETE CASCADE,
    Name TEXT NOT NULL,
    -- we add this here because its a soul link if one dies they all die
    PokemonAreAlive INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE Pokemon (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    RouteId INTEGER NOT NULL REFERENCES Routes (Id) ON DELETE CASCADE,
    TrainerId INTEGER NOT NULL REFERENCES Trainers (Id),
    Name TEXT NOT NULL
);
